### PR TITLE
Set InsecureSkipVerify on Windows

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by gmfeinberg** [comment]
Hi mattn,
Thanks for providing this. Oracle has some contributor paperwork that's required in order to directly merge user contributions. Have you seen it? The link is https://github.com/oracle/nosql-go-sdk/blob/master/CONTRIBUTING.md.

If this is a problem let us know. Thanks again!
George

**Comment by mattn** [comment]
Well... It's hard to do. Especially, I don't want to write my state/address or phone numbers etc. If I will abandon the copyright of this patch, can you please merge this change as you do same to mine? My hope is only that this problem will be fixed soon.

**Comment by gmfeinberg** [comment]
Thanks! I understand. We'll look at doing this ourselves; it's pretty safe.

**Comment by mattn** [comment]
FYI, I will make another pull-request that fixes to use path/filepath package instead of path package. Thanks.

**Pull request closed without merging**
